UserBundle\Entity\Command:
    type: entity
    table: command
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: last_name
        dob:
            type: date
            nullable: false
        address:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        city:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        state:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        zip:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        phone:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        contactEmail:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: contact_email
        creationDate:
            type: date
            nullable: false
            column: creation_date
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        status:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
