UserBundle\Entity\Complaint:
    type: entity
    table: complaint
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        complaintDate:
            type: date
            nullable: false
            column: complaint_date
        subject:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        content:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        state:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
