UserBundle\Entity\Event:
    type: entity
    table: event
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        location:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        startdate:
            type: date
            nullable: false
            column: startDate
        enddate:
            type: date
            nullable: false
            column: endDate
        checked:
            type: integer
            nullable: false
            options:
                unsigned: false
        participants:
            type: integer
            nullable: false
            options:
                unsigned: false
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
