UserBundle\Entity\Matching:
    type: entity
    table: matching
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        user1:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        user2:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
