UserBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        address:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        longitude:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        latitude:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
        description:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        category:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        image:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        note:
            type: float
            nullable: false
            precision: 10
            scale: 0
        countnote:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: countNote
    lifecycleCallbacks: {  }
