UserBundle\Entity\UserScore:
    type: entity
    table: user_score
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        iduser:
            type: integer
            nullable: false
            options:
                unsigned: false
        theme:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        score:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
