UserBundle\Entity\Wishlist:
    type: entity
    table: wishlist
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        prodName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: prod_name
        description:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        emailClient:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: email_client
        prodPrice:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: prod_price
    lifecycleCallbacks: {  }
